apiVersion: v1
kind: Service
metadata:
  name: svc-load-balancer
  namespace: default
spec:
  selector:
    app: nginx
    env: prod
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
