apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  namespace: default
  labels:
    app: nginx
    env: prod
spec:
  selector:
    matchLabels:
      app: nginx
      env: prod
  replicas: 2
  revisionHistoryLimit: 3

  template:
    metadata:
      labels:
        app: nginx
        env: prod
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
